<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJdOCw0n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJdOCw0n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJdOCw0n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJdOCw0n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJdOCw0n\App_KernelDevDebugContainer([
    'container.build_hash' => 'JdOCw0n',
    'container.build_id' => 'aea46511',
    'container.build_time' => 1729723275,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJdOCw0n');
