<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerJdOCw0n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJdOCw0n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJdOCw0n.legacy');
=======
if (\class_exists(\ContainerCcxZ6m7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCcxZ6m7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCcxZ6m7.legacy');
>>>>>>> a94ef9c2cd5ca94689bd5f6ec7429cdb8a85fbcb

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerJdOCw0n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJdOCw0n\App_KernelDevDebugContainer([
    'container.build_hash' => 'JdOCw0n',
    'container.build_id' => 'aea46511',
    'container.build_time' => 1729723275,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJdOCw0n');
=======
    \class_alias(\ContainerCcxZ6m7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCcxZ6m7\App_KernelDevDebugContainer([
    'container.build_hash' => 'CcxZ6m7',
    'container.build_id' => 'de4fa8bd',
    'container.build_time' => 1729717667,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCcxZ6m7');
>>>>>>> a94ef9c2cd5ca94689bd5f6ec7429cdb8a85fbcb
